' ******************************************************************************
' swxJRNL.swj - journal recorded on 04/13/25 by USER
' *****************************************************************************
Dim swApp As Object

Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long

Sub main()

Set swApp = Application.SldWorks

swApp.ActivateDoc2 "R7_ENG_0000.SLDASM", False, longstatus
Set Part = swApp.ActiveDoc
Set Part = swApp.ActiveDoc
Dim myModelView As Object
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized

' Redraw
Part.GraphicsRedraw2
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.155424112682248039, 0.05235987755983000091, 0.06779243428060155452, 0.2901983756116237601, 0.05888737216048411938
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01227032468544063393, 0, 0.06779243428060155452, 0.2901983756116237601, 0.05888737216048411938
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.08998238102656465343, 0, 0.06779243428060155452, 0.2901983756116237601, 0.05888737216048411938
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.04499119051328232671, 0, 0.06779243428060155452, 0.2901983756116237601, 0.05888737216048411938
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.08998238102656465343, -0.01495996501709428821, 0.06779243428060155452, 0.2901983756116237601, 0.05888737216048411938
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008180216456960421462, -0.007479982508547144103, 0.06779243428060155452, 0.2901983756116237601, 0.05888737216048411938
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01636043291392084292, -0.02243994752564143144, 0.06779243428060155452, 0.2901983756116237601, 0.05888737216048411938
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01227032468544063393, 0, 0.06779243428060155452, 0.2901983756116237601, 0.05888737216048411938
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.2617669266227334868, -0.1645596151880371616, 0.06779243428060155452, 0.2901983756116237601, 0.05888737216048411938
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02045054114240105539, -0.007479982508547144103, 0.06779243428060155452, 0.2901983756116237601, 0.05888737216048411938
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007479982508547144103, 0.06779243428060155452, 0.2901983756116237601, 0.05888737216048411938
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01495996501709428821, 0.06779243428060155452, 0.2901983756116237601, 0.05888737216048411938
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004090108228480210731, 0.02243994752564143144, 0.06779243428060155452, 0.2901983756116237601, 0.05888737216048411938
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004090108228480210731, 0.03739991254273571791, 0.06779243428060155452, 0.2901983756116237601, 0.05888737216048411938
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.184054870281609495, 0.007479982508547144103, 0.06779243428060155452, 0.2901983756116237601, 0.05888737216048411938
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.155424112682248039, -0.01495996501709428821, 0.06779243428060155452, 0.2901983756116237601, 0.05888737216048411938
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.09816259748352507142, -0.05235987755983000091, 0.06779243428060155452, 0.2901983756116237601, 0.05888737216048411938
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.07362194811264378969, -0.007479982508547144103, 0.06779243428060155452, 0.2901983756116237601, 0.05888737216048411938
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.06953183988416358763, 0, 0.06779243428060155452, 0.2901983756116237601, 0.05888737216048411938

' Roll View
Dim swModelView As Object
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01636043291392084292, 0, 0.04844210349030220186, 0.2641305991386104779, 0.07116846180952052237
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02045054114240105539, 0.01495996501709428821, 0.04844210349030220186, 0.2641305991386104779, 0.07116846180952052237
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.09816259748352507142, 0.07479982508547143583, 0.04844210349030220186, 0.2641305991386104779, 0.07116846180952052237
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0613516234272031627, 0.02991993003418857641, 0.04844210349030220186, 0.2641305991386104779, 0.07116846180952052237
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.06544173165568337169, 0.04487989505128286288, 0.04844210349030220186, 0.2641305991386104779, 0.07116846180952052237
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03681097405632189484, 0.05235987755983000091, 0.04844210349030220186, 0.2641305991386104779, 0.07116846180952052237
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007479982508547144103, 0.04844210349030220186, 0.2641305991386104779, 0.07116846180952052237
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004090108228480210731, 0.04487989505128286288, 0.04844210349030220186, 0.2641305991386104779, 0.07116846180952052237
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004090108228480210731, 0.03739991254273571791, 0.04844210349030220186, 0.2641305991386104779, 0.07116846180952052237
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02045054114240105539, 0.05235987755983000091, 0.04844210349030220186, 0.2641305991386104779, 0.07116846180952052237
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01227032468544063393, 0.01495996501709428821, 0.04844210349030220186, 0.2641305991386104779, 0.07116846180952052237

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.1472438962252875794, 0.1869995627136785965, -0.04945629352758373898, 0.1842247839299080425, 0.04749496711679057626
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01227032468544063393, 0.01495996501709428821, -0.04945629352758373898, 0.1842247839299080425, 0.04749496711679057626
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.2331361690233720307, 0.1720395976965843066, -0.04945629352758373898, 0.1842247839299080425, 0.04749496711679057626
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0572615151987229537, 0.02243994752564143144, -0.04945629352758373898, 0.1842247839299080425, 0.04749496711679057626
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.08180216456960422156, 0.01495996501709428821, -0.04945629352758373898, 0.1842247839299080425, 0.04749496711679057626
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01636043291392084292, 0.007479982508547144103, -0.04945629352758373898, 0.1842247839299080425, 0.04749496711679057626
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004090108228480210731, 0, -0.04945629352758373898, 0.1842247839299080425, 0.04749496711679057626
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004090108228480210731, 0, -0.04945629352758373898, 0.1842247839299080425, 0.04749496711679057626
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02863075759936147685, -0.05983986006837715282, -0.04945629352758373898, 0.1842247839299080425, 0.04749496711679057626
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.06953183988416358763, -0.07479982508547143583, -0.04945629352758373898, 0.1842247839299080425, 0.04749496711679057626
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.04908129874176253571, -0.007479982508547144103, -0.04945629352758373898, 0.1842247839299080425, 0.04749496711679057626
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01636043291392084292, -0.02991993003418857641, -0.04945629352758373898, 0.1842247839299080425, 0.04749496711679057626
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.1267933550828865552, -0.01495996501709428821, -0.04945629352758373898, 0.1842247839299080425, 0.04749496711679057626
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004090108228480210731, 0, -0.04945629352758373898, 0.1842247839299080425, 0.04749496711679057626
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008180216456960421462, 0.01495996501709428821, -0.04945629352758373898, 0.1842247839299080425, 0.04749496711679057626
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004090108228480210731, 0.007479982508547144103, -0.04945629352758373898, 0.1842247839299080425, 0.04749496711679057626
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004090108228480210731, 0.06731984257692429086, -0.04945629352758373898, 0.1842247839299080425, 0.04749496711679057626
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008180216456960421462, 0.07479982508547143583, -0.04945629352758373898, 0.1842247839299080425, 0.04749496711679057626
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008180216456960421462, 0.02991993003418857641, -0.04945629352758373898, 0.1842247839299080425, 0.04749496711679057626
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01227032468544063393, 0.04487989505128286288, -0.04945629352758373898, 0.1842247839299080425, 0.04749496711679057626
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.03739991254273571791, -0.04945629352758373898, 0.1842247839299080425, 0.04749496711679057626
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008180216456960421462, 0.05235987755983000091, -0.04945629352758373898, 0.1842247839299080425, 0.04749496711679057626
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.03739991254273571791, -0.04945629352758373898, 0.1842247839299080425, 0.04749496711679057626
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02454064937088126785, 0.01495996501709428821, -0.04945629352758373898, 0.1842247839299080425, 0.04749496711679057626
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03272086582784168585, 0, -0.04945629352758373898, 0.1842247839299080425, 0.04749496711679057626
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008180216456960421462, -0.007479982508547144103, -0.04945629352758373898, 0.1842247839299080425, 0.04749496711679057626
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02454064937088126785, -0.007479982508547144103, -0.04945629352758373898, 0.1842247839299080425, 0.04749496711679057626
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02863075759936147685, -0.01495996501709428821, -0.04945629352758373898, 0.1842247839299080425, 0.04749496711679057626
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02454064937088126785, -0.02243994752564143144, -0.04945629352758373898, 0.1842247839299080425, 0.04749496711679057626
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01636043291392084292, -0.01495996501709428821, -0.04945629352758373898, 0.1842247839299080425, 0.04749496711679057626

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01227032468544063393, 0.06731984257692429086, -0.07109971455594177314, 0.2914871279789821301, 0.04722748885779992634
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01227032468544063393, 0.1346396851538485817, -0.07109971455594177314, 0.2914871279789821301, 0.04722748885779992634
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008180216456960421462, 0.0822798075940185808, -0.07109971455594177314, 0.2914871279789821301, 0.04722748885779992634
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004090108228480210731, 0.06731984257692429086, -0.07109971455594177314, 0.2914871279789821301, 0.04722748885779992634
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004090108228480210731, 0.05983986006837715282, -0.07109971455594177314, 0.2914871279789821301, 0.04722748885779992634
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007479982508547144103, -0.07109971455594177314, 0.2914871279789821301, 0.04722748885779992634
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01227032468544063393, -0.03739991254273571791, -0.07109971455594177314, 0.2914871279789821301, 0.04722748885779992634
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01227032468544063393, -0.03739991254273571791, -0.07109971455594177314, 0.2914871279789821301, 0.04722748885779992634
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008180216456960421462, -0.01495996501709428821, -0.07109971455594177314, 0.2914871279789821301, 0.04722748885779992634
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008180216456960421462, -0.01495996501709428821, -0.07109971455594177314, 0.2914871279789821301, 0.04722748885779992634
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004090108228480210731, -0.02243994752564143144, -0.07109971455594177314, 0.2914871279789821301, 0.04722748885779992634
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004090108228480210731, -0.007479982508547144103, -0.07109971455594177314, 0.2914871279789821301, 0.04722748885779992634
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007479982508547144103, -0.07109971455594177314, 0.2914871279789821301, 0.04722748885779992634
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007479982508547144103, -0.07109971455594177314, 0.2914871279789821301, 0.04722748885779992634
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004090108228480210731, 0, -0.07109971455594177314, 0.2914871279789821301, 0.04722748885779992634
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004090108228480210731, -0.007479982508547144103, -0.07109971455594177314, 0.2914871279789821301, 0.04722748885779992634
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02991993003418857641, -0.07109971455594177314, 0.2914871279789821301, 0.04722748885779992634
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007479982508547144103, -0.07109971455594177314, 0.2914871279789821301, 0.04722748885779992634
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007479982508547144103, -0.07109971455594177314, 0.2914871279789821301, 0.04722748885779992634
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004090108228480210731, -0.007479982508547144103, -0.07109971455594177314, 0.2914871279789821301, 0.04722748885779992634
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008180216456960421462, 0.007479982508547144103, -0.07109971455594177314, 0.2914871279789821301, 0.04722748885779992634
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008180216456960421462, 0.03739991254273571791, -0.07109971455594177314, 0.2914871279789821301, 0.04722748885779992634
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007479982508547144103, -0.07109971455594177314, 0.2914871279789821301, 0.04722748885779992634
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01495996501709428821, -0.07109971455594177314, 0.2914871279789821301, 0.04722748885779992634
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02991993003418857641, -0.07109971455594177314, 0.2914871279789821301, 0.04722748885779992634
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01495996501709428821, -0.07109971455594177314, 0.2914871279789821301, 0.04722748885779992634
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02991993003418857641, -0.07109971455594177314, 0.2914871279789821301, 0.04722748885779992634
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007479982508547144103, -0.07109971455594177314, 0.2914871279789821301, 0.04722748885779992634
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004090108228480210731, 0.02243994752564143144, -0.07109971455594177314, 0.2914871279789821301, 0.04722748885779992634
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01495996501709428821, -0.07109971455594177314, 0.2914871279789821301, 0.04722748885779992634
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02243994752564143144, -0.07109971455594177314, 0.2914871279789821301, 0.04722748885779992634
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004090108228480210731, 0.01495996501709428821, -0.07109971455594177314, 0.2914871279789821301, 0.04722748885779992634
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02243994752564143144, -0.07109971455594177314, 0.2914871279789821301, 0.04722748885779992634
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004090108228480210731, 0.02243994752564143144, -0.07109971455594177314, 0.2914871279789821301, 0.04722748885779992634
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01227032468544063393, 0.03739991254273571791, -0.07109971455594177314, 0.2914871279789821301, 0.04722748885779992634
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004090108228480210731, 0.007479982508547144103, -0.07109971455594177314, 0.2914871279789821301, 0.04722748885779992634
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004090108228480210731, 0.007479982508547144103, -0.07109971455594177314, 0.2914871279789821301, 0.04722748885779992634
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008180216456960421462, 0.02243994752564143144, -0.07109971455594177314, 0.2914871279789821301, 0.04722748885779992634
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004090108228480210731, 0.01495996501709428821, -0.07109971455594177314, 0.2914871279789821301, 0.04722748885779992634
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008180216456960421462, 0.02243994752564143144, -0.07109971455594177314, 0.2914871279789821301, 0.04722748885779992634
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004090108228480210731, 0.01495996501709428821, -0.07109971455594177314, 0.2914871279789821301, 0.04722748885779992634
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007479982508547144103, -0.07109971455594177314, 0.2914871279789821301, 0.04722748885779992634
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004090108228480210731, 0, -0.07109971455594177314, 0.2914871279789821301, 0.04722748885779992634
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02991993003418857641, -0.07109971455594177314, 0.2914871279789821301, 0.04722748885779992634
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004090108228480210731, 0.01495996501709428821, -0.07109971455594177314, 0.2914871279789821301, 0.04722748885779992634

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007479982508547144103, -0.07066603458690678963, 0.2946344619341374482, 0.01414234781753975767
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01227032468544063393, -0.02991993003418857641, -0.07066603458690678963, 0.2946344619341374482, 0.01414234781753975767
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01227032468544063393, -0.007479982508547144103, -0.07066603458690678963, 0.2946344619341374482, 0.01414234781753975767
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.06544173165568337169, -0.06731984257692429086, -0.07066603458690678963, 0.2946344619341374482, 0.01414234781753975767
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02454064937088126785, 0, -0.07066603458690678963, 0.2946344619341374482, 0.01414234781753975767
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007479982508547144103, -0.07066603458690678963, 0.2946344619341374482, 0.01414234781753975767
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007479982508547144103, -0.07066603458690678963, 0.2946344619341374482, 0.01414234781753975767
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004090108228480210731, 0, -0.07066603458690678963, 0.2946344619341374482, 0.01414234781753975767
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004090108228480210731, -0.01495996501709428821, -0.07066603458690678963, 0.2946344619341374482, 0.01414234781753975767

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
boolstatus = Part.Extension.SelectByRay(-0.06519220478725173962, 0.2961326024986998817, 0.0116765170415646935, 0.9461783726739351197, 0.02556378370999474667, -0.3226344371677217771, 0.0001803703353412537441, 2, True, 0, 0)
boolstatus = Part.Extension.SelectByRay(-0.07703310524664175318, 0.2966511035208885261, 0.01352240936989801412, 0.9461783726739351197, 0.02556378370999474667, -0.3226344371677217771, 0.0001803703353412537441, 2, True, 0, 0)

' Create ConcentricMateFeatureData
Dim MateData As ConcentricMateFeatureData
Set MateData = Part.CreateMateData(1)

' Set the Entities To Mate
Dim EntitiesToMate(1) As Object
Set EntitiesToMate(0) = Part.SelectionManager.GetSelectedObject6(1, -1)
Set EntitiesToMate(1) = Part.SelectionManager.GetSelectedObject6(2, -1)
Dim EntitiesToMateVar As Variant
EntitiesToMateVar = EntitiesToMate
MateData.EntitiesToMate = (EntitiesToMateVar)

' Set the Mate Alignment
MateData.MateAlignment = 1

' Set the Lock Rotation
MateData.LockRotation = False

' Create the mate
Dim MateFeature As Feature
Set MateFeature = Part.CreateMate(MateData)
Part.ClearSelection2 True
Part.EditRebuild3


' Save
Dim swErrors As Long
Dim swWarnings As Long
boolstatus = Part.Save3(1, swErrors, swWarnings)
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
swApp.ExitApp
End Sub
