' ******************************************************************************
' swxJRNL.swj - journal recorded on 03/01/25 by USER
' *****************************************************************************
Dim swApp As Object

Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long

Sub main()

Set swApp = Application.SldWorks

swApp.ActivateDoc2 "R7_ENG_0000.SLDASM", False, longstatus
Set Part = swApp.ActiveDoc
Set Part = swApp.ActiveDoc
Dim myModelView As Object
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
boolstatus = Part.Extension.SelectByID2("@Radax prot 3-1-1@R7_ENG_0000", "AXIS", 0.07444633880708298457, 0.3393685608374586993, 0.3328432869539856287, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByRay(-0.01333624332298199988, 0.2954536738135971063, 0.06915074263372389396, -0.2962959612503273665, -0.1617726200347805177, -0.9412960866559614281, 0.0004860009538327544746, 2, True, 0, 0)

' Redraw
Part.GraphicsRedraw2
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("@Radax prot 3-1-1@R7_ENG_0000", "AXIS", 0.07444633880708298457, 0.3393685608374586993, 0.3328432869539856287, True, 1, Nothing, 0)
boolstatus = Part.Extension.SelectByRay(-0.01333624332298199988, 0.2954536738135971063, 0.06915074263372389396, -0.2962959612503273665, -0.1617726200347805177, -0.9412960866559614281, 0.0004860009538327544746, 2, True, 1, 0)

' Create ParallelMateFeatureData
Dim MateData As ParallelMateFeatureData
Set MateData = Part.CreateMateData(3)

' Set the Entities To Mate
Dim EntitiesToMate(1) As Object
Set EntitiesToMate(0) = Part.SelectionManager.GetSelectedObject6(1, -1)
Set EntitiesToMate(1) = Part.SelectionManager.GetSelectedObject6(2, -1)
Dim EntitiesToMateVar As Variant
EntitiesToMateVar = EntitiesToMate
MateData.EntitiesToMate = (EntitiesToMateVar)

' Set the Mate Alignment
MateData.MateAlignment = 1

' Create the mate
Dim MateFeature As Feature
Set MateFeature = Part.CreateMate(MateData)
Part.ClearSelection2 True
Part.EditRebuild3

boolstatus = Part.Extension.SelectByID2("Wspólnie10@R7_ENG_3000_Feed2-1@R7_ENG_0000", "MATE", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Koncentryczne28@R7_ENG_3000_Feed2-1@R7_ENG_0000", "MATE", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Wspólnie9@R7_ENG_3000_Feed2-1@R7_ENG_0000", "MATE", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Wspólnie10@R7_ENG_3000_Feed2-1@R7_ENG_0000", "MATE", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Wspólnie10@R7_ENG_3000_Feed2-1@R7_ENG_0000", "MATE", 0, 0, 0, False, 0, Nothing, 0)

' Isolate
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Wspólnie10@R7_ENG_3000_Feed2-1@R7_ENG_0000", "MATE", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.RunCommand(2726, "")
Part.ClearSelection2 True
boolstatus = Part.Extension.RunCommand(2732, "")

' Save
Dim swErrors As Long
Dim swWarnings As Long
boolstatus = Part.Save3(1, swErrors, swWarnings)
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004090108228480210731, 0, 0.04481014941242733585, 0.4739532207457415325, -0.06235753882680228344
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03272086582784168585, -0.3216392478675271782, 0.04481014941242733585, 0.4739532207457415325, -0.06235753882680228344
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004090108228480210731, -0.4487989505128286427, 0.04481014941242733585, 0.4739532207457415325, -0.06235753882680228344
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008180216456960421462, -0.1047197551196600018, 0.04481014941242733585, 0.4739532207457415325, -0.06235753882680228344
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03681097405632189484, -0.5385587406153943268, 0.04481014941242733585, 0.4739532207457415325, -0.06235753882680228344
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.1795195802051314515, 0.04481014941242733585, 0.4739532207457415325, -0.06235753882680228344
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004090108228480210731, -0.1421196676623957267, 0.04481014941242733585, 0.4739532207457415325, -0.06235753882680228344
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.1271597026453014367, 0.04481014941242733585, 0.4739532207457415325, -0.06235753882680228344
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.05235987755983000091, 0.04481014941242733585, 0.4739532207457415325, -0.06235753882680228344
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02454064937088126785, 0.02243994752564143144, 0.04481014941242733585, 0.4739532207457415325, -0.06235753882680228344
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.04090108228480211078, -0.1944795452222257415, 0.04481014941242733585, 0.4739532207457415325, -0.06235753882680228344
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007479982508547144103, 0.04481014941242733585, 0.4739532207457415325, -0.06235753882680228344
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007479982508547144103, 0.04481014941242733585, 0.4739532207457415325, -0.06235753882680228344
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004090108228480210731, -0.007479982508547144103, 0.04481014941242733585, 0.4739532207457415325, -0.06235753882680228344
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.06953183988416358763, -0.2019595277307728587, 0.04481014941242733585, 0.4739532207457415325, -0.06235753882680228344
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.1104329221689657053, -0.02243994752564143144, 0.04481014941242733585, 0.4739532207457415325, -0.06235753882680228344
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.155424112682248039, -0.05983986006837715282, 0.04481014941242733585, 0.4739532207457415325, -0.06235753882680228344
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.2699471430796939186, 0.4039190554615457174, 0.04481014941242733585, 0.4739532207457415325, -0.06235753882680228344

' Roll View
Dim swModelView As Object
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.04090108228480211078, 0.03739991254273571791, -0.01346448013907775021, 0.3183313216890155672, 0.07996380986571693938

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.06953183988416358763, 0.03739991254273571791, 0.07812520812336742893, 0.3964951908988041396, 0.0004461048677057988243
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004090108228480210731, 0.007479982508547144103, 0.07812520812336742893, 0.3964951908988041396, 0.0004461048677057988243
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02454064937088126785, 0, 0.07812520812336742893, 0.3964951908988041396, 0.0004461048677057988243
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01227032468544063393, 0, 0.07812520812336742893, 0.3964951908988041396, 0.0004461048677057988243
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01636043291392084292, 0.01495996501709428821, 0.07812520812336742893, 0.3964951908988041396, 0.0004461048677057988243
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.1022527057120052735, 0.1121997376282071607, 0.07812520812336742893, 0.3964951908988041396, 0.0004461048677057988243

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02243994752564143144, 0.01417329795629029832, 0.3288745108775970039, -0.01642889622149823481
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.04908129874176253571, 0.0822798075940185808, 0.01417329795629029832, 0.3288745108775970039, -0.01642889622149823481
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.1227032468544063254, -0.1495996501709428717, 0.01417329795629029832, 0.3288745108775970039, -0.01642889622149823481
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.04499119051328232671, -0.07479982508547143583, 0.01417329795629029832, 0.3288745108775970039, -0.01642889622149823481
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.08589227279808443749, -0.05235987755983000091, 0.01417329795629029832, 0.3288745108775970039, -0.01642889622149823481
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.06544173165568337169, -0.05983986006837715282, 0.01417329795629029832, 0.3288745108775970039, -0.01642889622149823481
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.04499119051328232671, -0.02243994752564143144, 0.01417329795629029832, 0.3288745108775970039, -0.01642889622149823481
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007479982508547144103, 0.01417329795629029832, 0.3288745108775970039, -0.01642889622149823481
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008180216456960421462, -0.2393594402735086113, 0.01417329795629029832, 0.3288745108775970039, -0.01642889622149823481
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004090108228480210731, -0.07479982508547143583, 0.01417329795629029832, 0.3288745108775970039, -0.01642889622149823481
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02454064937088126785, -0.3365992128846214682, 0.01417329795629029832, 0.3288745108775970039, -0.01642889622149823481
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008180216456960421462, -0.0822798075940185808, 0.01417329795629029832, 0.3288745108775970039, -0.01642889622149823481
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004090108228480210731, -0.04487989505128286288, 0.01417329795629029832, 0.3288745108775970039, -0.01642889622149823481
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004090108228480210731, -0.007479982508547144103, 0.01417329795629029832, 0.3288745108775970039, -0.01642889622149823481
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004090108228480210731, 0.1047197551196600018, 0.01417329795629029832, 0.3288745108775970039, -0.01642889622149823481
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004090108228480210731, 0.2094395102393200037, 0.01417329795629029832, 0.3288745108775970039, -0.01642889622149823481
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01636043291392084292, 0.1196797201367543056, 0.01417329795629029832, 0.3288745108775970039, -0.01642889622149823481
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02045054114240105539, 0.2393594402735086113, 0.01417329795629029832, 0.3288745108775970039, -0.01642889622149823481

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
swApp.ExitApp
End Sub
