' ******************************************************************************
' swxJRNL.swj - journal recorded on 04/13/25 by USER
' *****************************************************************************
Dim swApp As Object

Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long

Sub main()

Set swApp = Application.SldWorks

swApp.ActivateDoc2 "R7_ENG_1400_Injector.SLDASM", False, longstatus
Set Part = swApp.ActiveDoc
Set Part = swApp.ActiveDoc
Dim myModelView As Object
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized

' Redraw
Part.GraphicsRedraw2
Set Part = swApp.ActiveDoc
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 22
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
swApp.ActivateDoc2 "R7_ENG_1401_Injector.SLDPRT", False, longstatus
Set Part = swApp.ActiveDoc
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007479982508547144103, 0.003517243336812470034, -0.007868381013853564809, 0.005997958641614786757
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007479982508547144103, 0.003517243336812470034, -0.007868381013853564809, 0.005997958641614786757
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007479982508547144103, 0.003517243336812470034, -0.007868381013853564809, 0.005997958641614786757
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01495996501709428821, 0.003517243336812470034, -0.007868381013853564809, 0.005997958641614786757
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01495996501709428821, 0.003517243336812470034, -0.007868381013853564809, 0.005997958641614786757
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007479982508547144103, 0.003517243336812470034, -0.007868381013853564809, 0.005997958641614786757
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007479982508547144103, 0.003517243336812470034, -0.007868381013853564809, 0.005997958641614786757
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01495996501709428821, 0.003517243336812470034, -0.007868381013853564809, 0.005997958641614786757
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004090108228480210731, 0.02243994752564143144, 0.003517243336812470034, -0.007868381013853564809, 0.005997958641614786757
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01495996501709428821, 0.003517243336812470034, -0.007868381013853564809, 0.005997958641614786757
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01495996501709428821, 0.003517243336812470034, -0.007868381013853564809, 0.005997958641614786757
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01495996501709428821, 0.003517243336812470034, -0.007868381013853564809, 0.005997958641614786757
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004090108228480210731, 0.01495996501709428821, 0.003517243336812470034, -0.007868381013853564809, 0.005997958641614786757
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007479982508547144103, 0.003517243336812470034, -0.007868381013853564809, 0.005997958641614786757
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007479982508547144103, 0.003517243336812470034, -0.007868381013853564809, 0.005997958641614786757
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007479982508547144103, 0.003517243336812470034, -0.007868381013853564809, 0.005997958641614786757
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004090108228480210731, 0.01495996501709428821, 0.003517243336812470034, -0.007868381013853564809, 0.005997958641614786757
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007479982508547144103, 0.003517243336812470034, -0.007868381013853564809, 0.005997958641614786757
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007479982508547144103, 0.003517243336812470034, -0.007868381013853564809, 0.005997958641614786757
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007479982508547144103, 0.003517243336812470034, -0.007868381013853564809, 0.005997958641614786757
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007479982508547144103, 0.003517243336812470034, -0.007868381013853564809, 0.005997958641614786757
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007479982508547144103, 0.003517243336812470034, -0.007868381013853564809, 0.005997958641614786757
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007479982508547144103, 0.003517243336812470034, -0.007868381013853564809, 0.005997958641614786757
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007479982508547144103, 0.003517243336812470034, -0.007868381013853564809, 0.005997958641614786757
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007479982508547144103, 0.003517243336812470034, -0.007868381013853564809, 0.005997958641614786757
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004090108228480210731, 0.01495996501709428821, 0.003517243336812470034, -0.007868381013853564809, 0.005997958641614786757
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007479982508547144103, 0.003517243336812470034, -0.007868381013853564809, 0.005997958641614786757
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007479982508547144103, 0.003517243336812470034, -0.007868381013853564809, 0.005997958641614786757
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004090108228480210731, 0.007479982508547144103, 0.003517243336812470034, -0.007868381013853564809, 0.005997958641614786757
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007479982508547144103, 0.003517243336812470034, -0.007868381013853564809, 0.005997958641614786757
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007479982508547144103, 0.003517243336812470034, -0.007868381013853564809, 0.005997958641614786757
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007479982508547144103, 0.003517243336812470034, -0.007868381013853564809, 0.005997958641614786757
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007479982508547144103, 0.003517243336812470034, -0.007868381013853564809, 0.005997958641614786757
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007479982508547144103, 0.003517243336812470034, -0.007868381013853564809, 0.005997958641614786757
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01495996501709428821, 0.003517243336812470034, -0.007868381013853564809, 0.005997958641614786757
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008180216456960421462, 0.01495996501709428821, 0.003517243336812470034, -0.007868381013853564809, 0.005997958641614786757
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007479982508547144103, 0.003517243336812470034, -0.007868381013853564809, 0.005997958641614786757
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004090108228480210731, 0.007479982508547144103, 0.003517243336812470034, -0.007868381013853564809, 0.005997958641614786757
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007479982508547144103, 0.003517243336812470034, -0.007868381013853564809, 0.005997958641614786757
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007479982508547144103, 0.003517243336812470034, -0.007868381013853564809, 0.005997958641614786757
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007479982508547144103, 0.003517243336812470034, -0.007868381013853564809, 0.005997958641614786757

' Roll View
Dim swModelView As Object
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.06731984257692429086, -0.04126231175021644049, -0.002832429530460700562, 0.005999999999971805664
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02991993003418857641, -0.04126231175021644049, -0.002832429530460700562, 0.005999999999971805664
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02243994752564143144, -0.04126231175021644049, -0.002832429530460700562, 0.005999999999971805664
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.03739991254273571791, -0.04126231175021644049, -0.002832429530460700562, 0.005999999999971805664
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02243994752564143144, -0.04126231175021644049, -0.002832429530460700562, 0.005999999999971805664
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02243994752564143144, -0.04126231175021644049, -0.002832429530460700562, 0.005999999999971805664
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01495996501709428821, -0.04126231175021644049, -0.002832429530460700562, 0.005999999999971805664
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01495996501709428821, -0.04126231175021644049, -0.002832429530460700562, 0.005999999999971805664
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007479982508547144103, -0.04126231175021644049, -0.002832429530460700562, 0.005999999999971805664
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007479982508547144103, -0.04126231175021644049, -0.002832429530460700562, 0.005999999999971805664
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007479982508547144103, -0.04126231175021644049, -0.002832429530460700562, 0.005999999999971805664
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02243994752564143144, -0.04126231175021644049, -0.002832429530460700562, 0.005999999999971805664
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02991993003418857641, -0.04126231175021644049, -0.002832429530460700562, 0.005999999999971805664
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02243994752564143144, -0.04126231175021644049, -0.002832429530460700562, 0.005999999999971805664
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01495996501709428821, -0.04126231175021644049, -0.002832429530460700562, 0.005999999999971805664
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01495996501709428821, -0.04126231175021644049, -0.002832429530460700562, 0.005999999999971805664
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01495996501709428821, -0.04126231175021644049, -0.002832429530460700562, 0.005999999999971805664
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01495996501709428821, -0.04126231175021644049, -0.002832429530460700562, 0.005999999999971805664
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004090108228480210731, -0.01495996501709428821, -0.04126231175021644049, -0.002832429530460700562, 0.005999999999971805664
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01495996501709428821, -0.04126231175021644049, -0.002832429530460700562, 0.005999999999971805664
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007479982508547144103, -0.04126231175021644049, -0.002832429530460700562, 0.005999999999971805664
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007479982508547144103, -0.04126231175021644049, -0.002832429530460700562, 0.005999999999971805664
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007479982508547144103, -0.04126231175021644049, -0.002832429530460700562, 0.005999999999971805664
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007479982508547144103, -0.04126231175021644049, -0.002832429530460700562, 0.005999999999971805664
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007479982508547144103, -0.04126231175021644049, -0.002832429530460700562, 0.005999999999971805664
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007479982508547144103, -0.04126231175021644049, -0.002832429530460700562, 0.005999999999971805664
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007479982508547144103, -0.04126231175021644049, -0.002832429530460700562, 0.005999999999971805664
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007479982508547144103, -0.04126231175021644049, -0.002832429530460700562, 0.005999999999971805664
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01495996501709428821, -0.04126231175021644049, -0.002832429530460700562, 0.005999999999971805664
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01495996501709428821, -0.04126231175021644049, -0.002832429530460700562, 0.005999999999971805664
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01495996501709428821, -0.04126231175021644049, -0.002832429530460700562, 0.005999999999971805664
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007479982508547144103, -0.04126231175021644049, -0.002832429530460700562, 0.005999999999971805664
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004090108228480210731, 0, -0.04126231175021644049, -0.002832429530460700562, 0.005999999999971805664

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
boolstatus = Part.Extension.SelectByID2("Wytnij-wyci¹gniêcie3", "BODYFEATURE", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Wytnij-wyci¹gniêcie2", "BODYFEATURE", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Wytnij-wyci¹gniêcie3", "BODYFEATURE", 0, 0, 0, False, 0, Nothing, 0)
Part.ClearSelection2 True
' MSGBOX
' Czy zapisaæ zmiany w R7_ENG_1400_Injector.SLDASM?

Set Part = swApp.ActiveDoc
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set Part = swApp.ActiveDoc
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 22
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
swApp.ActivateDoc2 "R7_ENG_1401_Injector.SLDPRT", False, longstatus
Set Part = swApp.ActiveDoc
swApp.ExitApp
End Sub
